# Generated by Django 2.0.7 on 2018-07-06 10:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='details',
            field=tinymce.models.HTMLField(),
        ),
    ]
