# Generated by Django 2.0.7 on 2018-07-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='feature',
            field=models.BooleanField(choices=[(True, 'Feature'), (False, 'Bug')], default=False),
        ),
    ]
