# Generated by Django 2.0.7 on 2018-07-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0002_auto_20180706_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='feature',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_type',
            field=models.BooleanField(choices=[(True, 'Feature'), (False, 'Bug Fix')], default=False),
        ),
    ]
