# Generated by Django 2.0.7 on 2018-07-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0002_auto_20180706_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='details',
            field=models.TextField(),
        ),
    ]
