# Generated by Django 2.0.7 on 2018-07-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0004_upvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestion_type',
            new_name='is_suggestion',
        ),
    ]
