# Generated by Django 2.0.7 on 2018-07-06 13:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0006_auto_20180706_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
