# Generated by Django 2.0.7 on 2018-07-06 13:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0007_auto_20180706_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
