# Generated by Django 2.0.7 on 2018-07-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0008_auto_20180711_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usersuggestions.Comment'),
        ),
    ]
