# Generated by Django 2.0.7 on 2018-07-11 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersuggestions', '0009_upvote_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionAdminPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'not scheduled'), (1, 'to do'), (2, 'doing'), (3, 'done')], default='not scheduled')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'low'), (1, 'normal'), (2, 'high')], default=1, null=True)),
                ('date_time_started', models.DateTimeField(null=True)),
                ('expected_completion_date_time', models.DateTimeField(null=True)),
                ('developer_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersuggestions.Suggestion')),
            ],
        ),
    ]
