# Generated by Django 2.0.7 on 2018-07-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0010_suggestionadminpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersuggestions.Suggestion'),
        ),
    ]
