# Generated by Django 2.0.7 on 2018-07-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0012_auto_20180711_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersuggestions.Comment'),
        ),
    ]
