# Generated by Django 2.0.7 on 2018-07-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0013_auto_20180711_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionadminpage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'not scheduled'), (1, 'to do'), (2, 'doing'), (3, 'done')], default=0),
        ),
    ]
