# Generated by Django 2.0.7 on 2018-07-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0014_auto_20180711_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='admin_page_comment',
            field=models.BooleanField(default=False),
        ),
    ]
