# Generated by Django 2.0.7 on 2018-07-11 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0015_comment_admin_page_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionadminpage',
            name='date_time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestionadminpage',
            name='developer_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestionadminpage',
            name='expected_completion_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestionadminpage',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'low'), (1, 'normal'), (2, 'high')], default=1, null=True),
        ),
    ]
