# Generated by Django 2.0.7 on 2018-07-12 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersuggestions', '0018_auto_20180711_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_item_tyoe', models.PositiveSmallIntegerField(choices=[(1, 'comment'), (2, 'suggestion')])),
                ('date_time_marked', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'not scheduled'), (1, 'to do'), (2, 'doing'), (3, 'done')], default=0)),
                ('deemed_inappropriate', models.NullBooleanField()),
                ('admin_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_assigned', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersuggestions.Comment')),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersuggestions.Suggestion')),
            ],
        ),
    ]
