# Generated by Django 2.0.7 on 2018-07-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0019_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Spam'), (1, 'Hate Speech'), (2, 'Graphic Content'), (3, 'Harassment or Bullying')], default=0),
            preserve_default=False,
        ),
    ]
