# Generated by Django 2.0.7 on 2018-07-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0020_flag_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flag',
            old_name='flagged_item_tyoe',
            new_name='flagged_item_type',
        ),
    ]
