# Generated by Django 2.0.7 on 2018-07-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0021_auto_20180712_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionadminpage',
            name='is_current_winner',
            field=models.BooleanField(default=False),
        ),
    ]
