# Generated by Django 2.0.7 on 2018-07-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0022_suggestionadminpage_is_current_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionadminpage',
            name='estimated_completion_time',
            field=models.DurationField(null=True),
        ),
    ]
