# Generated by Django 2.0.7 on 2018-07-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0023_suggestionadminpage_estimated_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionadminpage',
            name='estimated_completion_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
