# Generated by Django 2.0.7 on 2018-07-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0025_auto_20180712_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionadminpage',
            name='date_time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestionadminpage',
            name='expected_completion_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
