# Generated by Django 2.0.7 on 2018-07-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0028_auto_20180712_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionadminpage',
            name='estimated_completion_time',
        ),
        migrations.AddField(
            model_name='suggestionadminpage',
            name='estimated_days_to_complete',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
