# Generated by Django 2.0.7 on 2018-07-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0029_auto_20180713_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionadminpage',
            name='in_current_voting_cycle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suggestionadminpage',
            name='was_successful',
            field=models.NullBooleanField(),
        ),
    ]
