# Generated by Django 2.0.7 on 2018-07-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0031_auto_20180713_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionadminpage',
            name='delay_submission',
            field=models.BooleanField(default=False),
        ),
    ]
