# Generated by Django 2.0.7 on 2018-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0032_suggestionadminpage_delay_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionadminpage',
            name='delay_submission',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='delay_submission',
            field=models.BooleanField(default=False),
        ),
    ]
