# Generated by Django 2.0.7 on 2018-07-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0035_promotedfeaturesuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedfeaturesuggestion',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotedfeaturesuggestion',
            name='start_date',
            field=models.DateField(),
        ),
    ]
