# Generated by Django 2.0.7 on 2018-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0036_auto_20180717_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionadminpage',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
