# Generated by Django 2.0.7 on 2018-07-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0038_auto_20180724_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='deemed_inappropriate',
        ),
        migrations.RemoveField(
            model_name='flag',
            name='status',
        ),
        migrations.AddField(
            model_name='flag',
            name='result',
            field=models.NullBooleanField(choices=[(True, 'Deemed Inappropriate'), (False, 'Not Deemed Inappropriate'), (None, 'To Do')]),
        ),
    ]
