# Generated by Django 2.0.7 on 2018-07-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0040_remove_flag_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersuggestions.Comment'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='result',
            field=models.NullBooleanField(choices=[(True, 'Deemed Inappropriate'), (False, 'Deemed Not Inappropriate'), (None, 'To Do')]),
        ),
        migrations.AlterField(
            model_name='flag',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersuggestions.Suggestion'),
        ),
    ]
