# Generated by Django 2.0.7 on 2018-07-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0042_remove_flag_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersuggestions.Comment'),
        ),
    ]
