# Generated by Django 2.0.7 on 2018-07-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0043_flag_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flag',
            old_name='admin_assigned',
            new_name='responsible_admin',
        ),
    ]
