# Generated by Django 2.0.7 on 2018-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0044_auto_20180727_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionadminpage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'not scheduled'), (1, 'scheduled'), (2, 'in progress'), (3, 'completed ')], default=0),
        ),
    ]
