# Generated by Django 2.0.7 on 2018-08-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0046_auto_20180727_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usersuggestions.Suggestion'),
        ),
    ]
