# Generated by Django 2.0.7 on 2018-07-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='date',
        ),
    ]
