# Generated by Django 2.0.7 on 2018-07-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_delivery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='current_delivery_method',
            field=models.BooleanField(default=True),
        ),
    ]
