# Generated by Django 2.0.7 on 2018-07-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_delivery_current_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='market.Delivery'),
        ),
    ]
