# Generated by Django 2.0.7 on 2018-07-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_storeitem_delivery_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
