# Generated by Django 2.0.7 on 2018-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20180705_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='is_coins',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercoins',
            name='coins',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
