# Generated by Django 2.0.7 on 2018-07-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_order_price_at_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_at_purchase',
            new_name='purchase_price',
        ),
    ]
