# Generated by Django 2.0.7 on 2018-07-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_auto_20180705_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
