# Generated by Django 2.0.7 on 2018-07-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_auto_20180705_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='purchase_price',
            new_name='total_purchase_price',
        ),
    ]
