# Generated by Django 2.0.7 on 2018-07-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_auto_20180705_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='coins_purchasable',
            field=models.BooleanField(default=False),
        ),
    ]
