# Generated by Django 2.0.7 on 2018-07-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_storeitem_coins_purchasable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='coins_purchasable',
            new_name='coins_purchasable_only',
        ),
    ]
