# Generated by Django 2.0.7 on 2018-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_auto_20180709_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='coins_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
