# Generated by Django 2.0.7 on 2018-07-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_storeitem_coins_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinsPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('coins_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='coins_price',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='coins_purchasable_only',
        ),
    ]
