# Generated by Django 2.0.7 on 2018-07-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_order_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
