# Generated by Django 2.0.7 on 2018-07-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_remove_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinhistory',
            name='coins_before',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
