# Generated by Django 2.0.7 on 2018-07-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersuggestions', '0034_userfavorites'),
        ('market', '0029_remove_usercoinhistory_coins_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinhistory',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersuggestions.Comment'),
        ),
        migrations.AddField(
            model_name='usercoinhistory',
            name='suggestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersuggestions.Suggestion'),
        ),
    ]
