# Generated by Django 2.0.7 on 2018-07-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_auto_20180716_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinhistory',
            name='charge',
            field=models.PositiveSmallIntegerField(choices=[(1, 'submission'), (2, 'upvote')], null=True),
        ),
    ]
