# Generated by Django 2.0.7 on 2018-07-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_usercoinhistory_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoinhistory',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usersuggestions.Comment'),
        ),
    ]
