# Generated by Django 2.0.7 on 2018-07-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_auto_20180716_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoinhistory',
            name='charge',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'submission'), (2, 'upvote')], null=True),
        ),
    ]
