# Generated by Django 2.0.7 on 2018-07-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0035_auto_20180716_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoinhistory',
            name='transaction',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'submission'), (2, 'upvote'), (3, 'referral'), (4, 'store purchase'), (5, 'initial signup'), (6, 'received referral'), (7, 'suggestion upvoted')], null=True),
        ),
    ]
