# Generated by Django 2.0.7 on 2018-07-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0036_auto_20180716_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoinhistory',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usersuggestions.Suggestion'),
        ),
    ]
