# Generated by Django 2.0.7 on 2018-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0038_auto_20180717_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoinhistory',
            name='transaction',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'submission'), (2, 'upvote'), (3, 'referral'), (4, 'store purchase'), (5, 'initial signup'), (6, 'received referral'), (7, 'suggestion upvoted'), (8, 'suggestion successful'), (9, 'feature suggestion promoted')], null=True),
        ),
    ]
