# Generated by Django 2.0.7 on 2018-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0040_auto_20180724_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
