# Generated by Django 2.0.7 on 2018-07-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0041_auto_20180727_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinspurchase',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
